# #############################################
# All of your changes (additions) go here.
FROM python:3.10-slim 

WORKDIR /app


COPY server.py .

EXPOSE 80

CMD ["python", "server.py"]
# #############################################